{
 "title": "App con S3, Kafka (Producer/Consumer) y DataBase",
 "description": "Desarrollo de contenedores Docker para crear ambiente adecuado emulando la ejecución de App/Kafka/S3/DB.",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "application",
    "label": "Application",
    "query": "label_values(up{group=~\"app|topic\"}, instance)"
   },
   {
    "name": "application_topic",
    "label": "Application topic",
    "query": "label_values(spring_integration_sources, application)"
   },
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(node_uname_info, instance)"
   },
   {
    "name": "maxmount",
    "label": "Max mount dir",
    "query": "query_result(topk(1,sort_desc (max(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.?|xfs\",mountpoint!~\".*pods.*\"}) by (mountpoint))))"
   },
   {
    "name": "instance_cadvisor",
    "label": "Instance cadvisor",
    "query": "label_values(cadvisor_version_info, instance)"
   },
   {
    "name": "broker_id",
    "label": "Broker Id",
    "query": "label_values(kafka_server_kafkaserver_brokerstate, instance)"
   },
   {
    "name": "producer_id",
    "label": "Producer",
    "query": "label_values(kafka_producer_app_info, client_id)"
   },
   {
    "name": "consumer_id",
    "label": "Consumer",
    "query": "label_values(kafka_consumer_app_info, instance)"
   },
   { "name": "env", "label": "Environment", "query": "label_values(env)" },
   {
    "name": "interval",
    "label": "Interval",
    "query": "5s,10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "percentile", "label": "Percentile", "query": "label_values(quantile)" }
  ]
 },
 "panels": [
  { "title": "Demo", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Request Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (uri, application, method) (http_server_requests_seconds_count{application=~\"$application\", uri!~\".*actuator.*\", uri!=\"/**\"})",
     "legendFormat": "{{application}} {{method}} [{{status}}] - {{uri}}"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 7, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"idle\"}[$__rate_interval])) * 100)",
     "legendFormat": "CPU Busy"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=~\"$node\"} / (node_memory_MemTotal_bytes{instance=~\"$node\"})))* 100",
     "legendFormat": "Used RAM Memory"
    },
    {
     "expr": "(ceph_cluster_total_used_bytes * 100) / ceph_cluster_total_bytes",
     "legendFormat": "Used S3 Capacity"
    }
   ]
  },
  {
   "title": "Active (hikaricp)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(hikaricp_connections_active{application=~\"$application\"}[1m]))"
    }
   ]
  },
  {
   "title": "ERROR logs (Apps)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(logback_events_total{application=~\"$application\", level=\"error\"}[$__interval])",
     "legendFormat": "{{application}}",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "Request por minuto",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 5 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{application=~\"$application\", uri!~\".*actuator.*\", uri!=\"/**\", uri!=\"UNKNOWN\", uri!=\"/**/favicon.ico\"}[1m]))",
     "legendFormat": "sadf"
    }
   ]
  },
  {
   "title": "Channel Throughput",
   "type": "graph",
   "gridPos": { "h": 3, "w": 10, "x": 7, "y": 5 },
   "repeat": "application_name",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(spring_integration_send_seconds_count{type=\"channel\",name=~\"output\",result=\"success\",application=~\"$application_topic\"}[$__rate_interval])",
     "legendFormat": "{{name}} [{{application}}]"
    },
    {
     "expr": "rate(spring_integration_send_seconds_count{type=\"channel\",name=~\"input\",result=\"success\",application=~\"$application_topic\"}[$__rate_interval])",
     "legendFormat": "{{name}} [{{application}}]"
    }
   ]
  },
  {
   "title": "Kafka",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Brokers Online",
     "type": "singlestat",
     "description": "Number of Brokers Online",
     "gridPos": { "h": 4, "w": 2, "x": 0, "y": 10 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "count(kafka_server_replicamanager_leadercount{job=\"kafka\",env=\"$env\",instance=~\"$broker_id\"})"
      }
     ]
    },
    {
     "title": "Active Controllers",
     "type": "singlestat",
     "description": "Number of active controllers in the cluster.",
     "gridPos": { "h": 4, "w": 3, "x": 2, "y": 10 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kafka_controller_kafkacontroller_activecontrollercount{job=\"kafka\",env=\"$env\",instance=~\"$broker_id\"})"
      }
     ]
    },
    {
     "title": "Online Partitions",
     "type": "singlestat",
     "description": "Partitions that are online",
     "gridPos": { "h": 4, "w": 3, "x": 5, "y": 10 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kafka_server_replicamanager_partitioncount{job=\"kafka\",env=\"$env\",instance=~\"$broker_id\"})"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 10 },
     "yaxes": [
      { "format": "percent", "label": "Cores" }
     ],
     "targets": [
      {
       "expr": "irate(process_cpu_seconds_total{job=\"kafka\",env=\"$env\",instance=~\"$broker_id\"}[5m])*100",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "JVM Memory Used",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 10 },
     "yaxes": [
      { "format": "bytes", "label": "Memory" }
     ],
     "targets": [
      {
       "expr": "sum without(area)(jvm_memory_bytes_used{job=\"kafka\",env=\"$env\",instance=~\"$broker_id\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Produce Request Per Sec",
     "type": "singlestat",
     "description": "Produce request rate.",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 14 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(rate(kafka_network_requestmetrics_requestspersec{job=\"kafka\",env=\"$env\",instance=~\"$broker_id\"}[1m]))"
      }
     ]
    },
    {
     "title": "Fetch Request Per Sec",
     "type": "singlestat",
     "description": "Fetch request rate.",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 14 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(rate(kafka_network_requestmetrics_requestspersec{job=\"kafka\",env=\"$env\",instance=~\"$broker_id\",request=\"FetchConsumer\"}[1m]))"
      }
     ]
    },
    {
     "title": "Bytes In Per Topic",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
     "yaxes": [
      { "format": "Bps", "label": "Bytes/s" }
     ],
     "targets": [
      {
       "expr": "sum without(instance)(rate(kafka_server_brokertopicmetrics_bytesinpersec{job=\"kafka\",env=\"$env\",instance=~\"$broker_id\",topic!=\"\"}[5m]))",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Bytes Out Per Topic",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
     "yaxes": [
      { "format": "Bps", "label": "Bytes/s" }
     ],
     "targets": [
      {
       "expr": "sum without(instance)(rate(kafka_server_brokertopicmetrics_bytesoutpersec{job=\"kafka\",env=\"$env\",instance=~\"$broker_id\",topic!=\"\"}[5m]))",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Error rate",
     "type": "graph",
     "description": "The average per-second number of record sends that resulted in errors.\n",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(kafka_producer_producer_metrics_record_error_total{job=\"producer\",env=\"$env\",client_id=~\"$producer_id\"}[$__rate_interval])",
       "legendFormat": "{{client_id}} - {{instance}}"
      }
     ]
    },
    {
     "title": "Producer - ResponseSendTimeMs",
     "type": "graph",
     "description": "A high value can imply the zero-copy from disk to the network is slow, or the network is the bottleneck because the network cant dequeue responses of the TCP socket as quickly as theyre being created. If the network buffer gets full, Kafka will block.\n",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_network_requestmetrics_responsesendtimems{job=\"kafka\",env=\"$env\",instance=~\"$broker_id\",quantile=~\"$percentile\",request=\"Produce\"}",
       "legendFormat": "{{instance}} - {{quantile}}"
      }
     ]
    },
    {
     "title": "Consumer - RemoteTimeMs",
     "type": "graph",
     "description": "A high value can imply a slow network connection. For fetch request, if the remote time is high, it could be that there is not enough data to give in a fetch response. This can happen when the consumer or replica is caught up and there is no new incoming data. If this is the case, remote time will be close to the max wait time, which is normal. Max wait time is configured via replica.fetch.wait.max.ms and fetch.max.wait.ms.\n",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_network_requestmetrics_remotetimems{job=\"kafka\",env=\"$env\",instance=~\"$broker_id\",quantile=~\"$percentile\",request=\"Fetch\"}",
       "legendFormat": "{{instance}} - {{quantile}}"
      }
     ]
    },
    {
     "title": "Channel Throughput",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 30 },
     "repeat": "application_name",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(spring_integration_send_seconds_count{type=\"channel\",name!=\"errorChannel\",name!=\"nullChannel\",result=\"success\",application=~\"$application_topic\"}[60s])",
       "legendFormat": "{{name}} [{{application}}]"
      }
     ]
    }
   ]
  },
  {
   "title": "S3 Ceph",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cluster Health",
     "type": "snuids-trafficlights-panel",
     "gridPos": { "h": 4, "w": 2, "x": 0, "y": 3 },
     "targets": [
      { "expr": "ceph_health_status", "legendFormat": "{{__name__}}" }
     ]
    },
    {
     "title": "OSD.0",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 2, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum without (instance) (ceph_osd_up{ceph_daemon=\"osd.0\"})"
      }
     ]
    },
    {
     "title": "Total OSDs",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 4, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count without (instance, ceph_daemon) (ceph_osd_up)"
      }
     ]
    },
    {
     "title": "Monitors",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 6, "y": 3 },
     "format": "none",
     "valueName": "current",
     "targets": [
      { "expr": "count(ceph_mon_quorum_status)" }
     ]
    },
    {
     "title": "Pools",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 8, "y": 3 },
     "format": "none",
     "valueName": "current",
     "targets": [
      { "expr": "count(ceph_pool_metadata)" }
     ]
    },
    {
     "title": "Objects",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 10, "y": 3 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "ceph_cluster_total_objects{cluster=\"$cluster\"}"
      }
     ]
    },
    {
     "title": "Utilization osd.0",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 2, "x": 12, "y": 3 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum without (instance, ceph_daemon) (ceph_osd_stat_bytes_used{ceph_daemon=\"osd.0\"}/ceph_osd_stat_bytes{ceph_daemon=\"osd.0\"})"
      }
     ]
    },
    {
     "title": "Throughput",
     "type": "graph",
     "gridPos": { "h": 7, "w": 10, "x": 14, "y": 3 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(irate(ceph_osd_op_w_in_bytes{}[$__rate_interval])) by (ceph_daemon)",
       "legendFormat": "Write {{ceph_daemon}}"
      },
      {
       "expr": "sum(irate(ceph_osd_op_r_out_bytes{}[$__rate_interval])) by (ceph_daemon)",
       "legendFormat": "Read {{ceph_daemon}}"
      }
     ]
    },
    {
     "title": "Avg OSD  Op  Latency",
     "type": "graph",
     "gridPos": { "h": 7, "w": 10, "x": 2, "y": 6 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "avg(rate(ceph_osd_op_w_latency_sum{}[$__rate_interval]) / rate(ceph_osd_op_w_latency_count{}[$__rate_interval]) >= 0) by (ceph_daemon)",
       "legendFormat": "Write {{ceph_daemon}}"
      },
      {
       "expr": "avg(rate(ceph_osd_op_r_latency_sum{}[$__rate_interval]) / rate(ceph_osd_op_r_latency_count{}[$__rate_interval]) >= 0) by (ceph_daemon)",
       "legendFormat": "Read {{ceph_daemon}}"
      }
     ]
    },
    {
     "title": "Capacity",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 0, "y": 7 },
     "format": "decbytes",
     "valueName": "current",
     "targets": [
      { "expr": "ceph_cluster_total_bytes" }
     ]
    },
    {
     "title": "Used Capacity",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 0, "y": 10 },
     "format": "decbytes",
     "valueName": "current",
     "targets": [
      { "expr": "ceph_cluster_total_used_bytes" }
     ]
    }
   ]
  },
  {
   "title": "Docker Container",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "containers",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 0, "y": 38 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "count(container_last_seen{image!=\"\"})"
      }
     ]
    },
    {
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 5, "x": 2, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "100 - (avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"idle\"}[$__rate_interval])) * 100)",
       "legendFormat": "CPU Busy"
      },
      {
       "expr": "(1 - (node_memory_MemAvailable_bytes{instance=~\"$node\"} / (node_memory_MemTotal_bytes{instance=~\"$node\"})))* 100",
       "legendFormat": "Used RAM Memory"
      },
      {
       "expr": "(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"}-node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"})*100 /(node_filesystem_avail_bytes {instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"}+(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"}-node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"}))",
       "legendFormat": "Used Max Mount($maxmount)"
      },
      {
       "expr": "(1 - ((node_memory_SwapFree_bytes{instance=~\"$node\"} + 1)/ (node_memory_SwapTotal_bytes{instance=~\"$node\"} + 1))) * 100",
       "legendFormat": "Used SWAP"
      }
     ]
    },
    {
     "title": "【$show_hostname】：Disk Space Used Basic(EXT?/XFS)",
     "type": "table-old",
     "description": "In this kanban: the total disk, usage, available, and usage rate are consistent with the values of the Size, Used, Avail, and Use% columns of the df command, and the value of Use% will be rounded to one decimal place, which will be more accurate .\n\nNote: The Use% algorithm in df is: (size-free) * 100 / (avail + (size-free)), the result is divisible by this value, non-divisible by this value is +1, and the unit of the result is %.\nRefer to the df command source code:",
     "gridPos": { "h": 3, "w": 9, "x": 7, "y": 38 },
     "targets": [
      {
       "expr": "node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-0",
       "legendFormat": "总量"
      },
      {
       "expr": "node_filesystem_avail_bytes {instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-0"
      },
      {
       "expr": "(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}) *100/(node_filesystem_avail_bytes {instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}+(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}))"
      }
     ]
    },
    {
     "title": "Network Traffic i/o",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 6, "w": 4, "x": 16, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "format": "decbytes",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_bytes_total{id=\"/\",instance=~\"$instance_cadvisor\"}[$__interval])) by (id)",
       "legendFormat": "Receive"
      },
      {
       "expr": "sum(rate(container_network_transmit_bytes_total{id=\"/\",instance=~\"$instance_cadvisor\"}[$__interval])) by (id)",
       "legendFormat": "Transmit"
      }
     ]
    },
    {
     "title": "Disk I/O",
     "type": "graph",
     "gridPos": { "h": 6, "w": 4, "x": 20, "y": 38 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "-sum(rate(node_disk_read_bytes_total{instance=~\"$node\"}[5m])) by (device)",
       "legendFormat": "OUT on /{{device}}"
      },
      {
       "expr": "sum(rate(node_disk_written_bytes_total{instance=~\"$node\"}[5m])) by (device)",
       "legendFormat": "IN on /{{device}}"
      }
     ]
    },
    {
     "title": "Total RAM",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 0, "y": 40 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(node_memory_MemTotal_bytes{instance=~\"$node\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "CPU Cores",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 0, "y": 42 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "count(node_cpu_seconds_total{instance=~\"$node\", mode='system'})"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "container_memory_usage_bytes{image!=\"\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Network Traffic i/o per container",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by (name) (rate(container_network_receive_bytes_total{image!=\"\"}[1m]))",
       "legendFormat": "{{name}} R"
      },
      {
       "expr": "sum by (name) (rate(container_network_transmit_bytes_total{image!=\"\"}[1m]))",
       "legendFormat": "{{name}} T"
      }
     ]
    },
    {
     "title": "Container CPU Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "rate(container_cpu_user_seconds_total{image!=\"\"}[5m]) * 100",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP Codes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{application=~\"$application\", status=~\"5..\"}[1m]))",
       "legendFormat": "5xx - Server Errors"
      },
      {
       "expr": "sum(rate(http_server_requests_seconds_count{application=~\"$application\", status=~\"4..\"}[1m]))",
       "legendFormat": "4xx - Client Errors"
      },
      {
       "expr": "sum(rate(http_server_requests_seconds_count{application=~\"$application\", status=~\"2..\"}[1m]))",
       "legendFormat": "2xx - Success"
      },
      {
       "expr": "sum(rate(http_server_requests_seconds_count{application=~\"$application\", status=~\"3..\"}[1m]))",
       "legendFormat": "3xx - Redirections"
      }
     ]
    },
    {
     "title": "Requests duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_sum{application=\"$application\", status!~\"5..\"}[1m]))/sum(rate(http_server_requests_seconds_count{application=\"$application\", status!~\"5..\"}[1m]))",
       "legendFormat": "Avg application"
      },
      {
       "expr": "max(http_server_requests_seconds_max{application=\"$application\", status!~\"5..\"})",
       "legendFormat": "Max application"
      },
      {
       "expr": "sum(rate(http_server_requests_seconds_sum{application=~\"$application_topic\", status!~\"5..\"}[1m]))/sum(rate(http_server_requests_seconds_count{application=~\"$application_topic\", status!~\"5..\"}[1m]))",
       "legendFormat": "Avg topic"
      },
      {
       "expr": "max(http_server_requests_seconds_max{application=~\"$application_topic\", status!~\"5..\"})",
       "legendFormat": "Max topic"
      }
     ]
    }
   ]
  }
 ]
}